version: "3.7"
services:

  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1111
      POSTGRES_USER: postgres
      POSTGRES_DB: csv_db
    hostname: db

  csv_server:
    build:
      context: .
    env_file:
      - .env
    command: ["/csv_server/csv_serv.sh"]
    ports:
      - 8000:8000
    depends_on:
      - db


