"""DB creation

Revision ID: dc5cfeb7457b
Revises: 
Create Date: 2023-07-04 15:47:07.929883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc5cfeb7457b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_csv',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('fileName', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_csv')
    # ### end Alembic commands ###
